#ifndef __VESC_H
#define __VESC_H	 
#include "sys.h"


/*VESC命令*/
typedef enum {
  CAN_PACKET_SET_DUTY = 0,
  CAN_PACKET_SET_CURRENT,//电流
  CAN_PACKET_SET_CURRENT_BRAKE,//电流制动
  CAN_PACKET_SET_RPM,//转速
  CAN_PACKET_SET_POS,//设置POS
  CAN_PACKET_FILL_RX_BUFFER,
  CAN_PACKET_FILL_RX_BUFFER_LONG,
  CAN_PACKET_PROCESS_RX_BUFFER,
  CAN_PACKET_PROCESS_SHORT_BUFFER,
  CAN_PACKET_STATUS,//速度处理存储
  CAN_PACKET_SET_CURRENT_REL,
  CAN_PACKET_SET_CURRENT_BRAKE_REL,
  CAN_PACKET_SET_CURRENT_HANDBRAKE,
  CAN_PACKET_SET_CURRENT_HANDBRAKE_REL,
  CAN_PACKET_STATUS_2,
  CAN_PACKET_STATUS_3,
  CAN_PACKET_STATUS_4,//位置处理与储存
  CAN_PACKET_PING,
  CAN_PACKET_PONG,
  CAN_PACKET_DETECT_APPLY_ALL_FOC,
  CAN_PACKET_DETECT_APPLY_ALL_FOC_RES,
  CAN_PACKET_CONF_CURRENT_LIMITS,
  CAN_PACKET_CONF_STORE_CURRENT_LIMITS,
  CAN_PACKET_CONF_CURRENT_LIMITS_IN,
  CAN_PACKET_CONF_STORE_CURRENT_LIMITS_IN,
  CAN_PACKET_CONF_FOC_ERPMS,
  CAN_PACKET_CONF_STORE_FOC_ERPMS,
  CAN_PACKET_STATUS_5,
  CAN_PACKET_POLL_TS5700N8501_STATUS
} VESC_CAN_COMMAND_ID;



/*
CAN_PACKET_STATUS->9
    0~3：速度
    4~5：总电流*10
    6~7：最近占空比*10

CAN_PACKET_STATUS_2->14
    0~3：单位消耗的总安培小时数*10000
    4~7：返回电池的总再生安培小时数*10000

CAN_PACKET_STATUS_3->15
    0~4：单位总耗电量*10000
    4~7：返回电池的可再生瓦时*10000

CAN_PACKET_STATUS_4->16
    0~1：MOSFET温度*10
    2~3：电机温度*10
    4~5：总输入电流*10，(以安培为单位)
    6~7：当前PID位置

CAN_PACKET_STATUS_5->27
    0~3：转速表读数
    4~5：输入电压*10
    6~7：保留
*/





//VESC的数据缓存
typedef struct
{
    u8 vesc_id;//VESC的id
    u8 vesc_data_9[8];//Packet Status=9(即CAN_PACKET_STATUS)的数据
    u8 vesc_data_14[8];//Packet Status=14(即CAN_PACKET_STATUS_2)的数据
    u8 vesc_data_15[8];//Packet Status=15(即CAN_PACKET_STATUS_3)的数据
    u8 vesc_data_16[8];//Packet Status=16(即CAN_PACKET_STATUS_4)的数据
    u8 vesc_data_27[8];//Packet Status=27(即CAN_PACKET_STATUS_5)的数据
    
    int32_t RPM;
    int16_t NowAngle;
    int16_t LastAngle;
    int16_t round_cnt;
}VESC_DATA_BUF;





void vesc_can_rx(uint32_t CAN_ExtId,u8*CAN_Rx_Data);
void VESC_Init(u8 CANx,VESC_DATA_BUF*VESC,u8 VESC_Num);
void VESC_Tx(uint8_t id,VESC_CAN_COMMAND_ID mode,int32_t Data);
int VESC_RPM(VESC_DATA_BUF VESC_DATA);
int VESC_POS(VESC_DATA_BUF VESC_DATA);
int VESC_CUR(VESC_DATA_BUF VESC_DATA);

#endif

